project_id = "udcttaicmvcpyoeixgrl"

[auth.email]
enable_confirmations = true

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
